package com.example.krahtzquizmaster

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import com.example.krahtzquizmaster.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {
    //binding class generated by our viewBinding feature
    lateinit var binding: ActivityMainBinding

    //This onCreate, creates my screen/activity
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        //inflating our layout from the binding class and setting it to our content
        //should be below the onCreate
        binding = ActivityMainBinding.inflate(layoutInflater)
        val view = binding.root

        setContentView(view)

//      update text with the use of the binding
//      binding.etUsername.setText("text Update working")

//      binding.btnStart.text = "Button text Updated"

        //TODO: Check username when button clicked
        binding.btnStart.setOnClickListener{
            //TODO: Validate if te username is valid
            //Getting the entered text (username)
            var username = binding.etUsername.text

            if(username.isNullOrBlank()){ //Check if username is filled in or not

                Log.d("AAA invalid Username", "Please fill in username")
                //TODO: Display Validation Message
            }else{
                //TODO: Navigate to QuestionActivity
                Log.d("AAA Captured Username: ", username.toString())//Debug
                //Define intent navigation
                val intent = Intent(this, CategoryActivity::class.java)

                //Pass extra information through to other activity
                intent.putExtra("username", username.toString())

                //Start intent
                startActivity(intent)
                //Remove activity from the backstack
                //finish()
            }

        }//end of button listener

    }//end of onCreate function
}