package com.example.krahtzquizmaster

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import com.example.krahtzquizmaster.databinding.ActivityQuestionBinding
import com.example.krahtzquizmaster.models.Constants.allQuestions
import com.example.krahtzquizmaster.models.Constants.geoQuestions
import com.example.krahtzquizmaster.models.Constants.getAllQuestions

class QuestionActivity : AppCompatActivity() {

    //binding class generated by our viewBinding feature
    lateinit var binding: ActivityQuestionBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        //inflating our layout from the binding class and setting it to our content
        binding = ActivityQuestionBinding.inflate(layoutInflater)
        val view = binding.root
        //setContentView divines which xml layout to use as my frontend
        setContentView(view)

        //Call to create questions
        getAllQuestions()
        //Create an instance of our questions
        val listOfAllQuestions = allQuestions //Create an instance of our questions
        val listOfGeoQuestions = geoQuestions //Create an instance of our geo questions
        val username = intent?.getStringExtra("username")

        Log.d("AAA First Question", listOfGeoQuestions[0].questionText)
        Log.d("AAA Second Question", listOfGeoQuestions[1].questionText)
        Log.d("AAA Third Question", listOfGeoQuestions[2].questionText)
        Log.d("AAA Fourth Question", listOfGeoQuestions[3].questionText)
        Log.d("AAA Fifth Question", listOfGeoQuestions[4].questionText)

        //TODO: Display question in our xml
        binding.username.title = "$username"

    }
}